### PR TITLE
Merge pull request #3 from adediranmuhydeen/main

### PR DESCRIPTION
**Pull request by adediranmuhydeen**
Merge

### CODE REVIEW

**Comment by adediranmuhydeen** [comment]
Commit

**Comment by adediranmuhydeen** [comment]
commited

**Review by adediranmuhydeen — COMMENTED** [review]
Good to merge

**Review by adediranmuhydeen — COMMENTED** [review]
Good to merge

**Review by GbadamosiIE — APPROVED** [review]
Great work!!!

**Pull request merged**
